name: scraper

on:
  schedule:
      - cron: '0 7 * * *'

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
  CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  TOKEN_URI: ${{ secrets.TOKEN_URI }}
  TYPE: ${{ secrets.TYPE }}

jobs:
  Daily-Ran:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set up credentials.json
        run: |
          echo '{
            "type": "${{ secrets.TYPE }}",
            "project_id": "${{ secrets.PROJECT_ID }}",
            "private_key_id": "${{ secrets.PRIVATE_KEY_ID }}",
            "private_key": "${{ secrets.PRIVATE_KEY }}",
            "client_email": "${{ secrets.CLIENT_EMAIL }}",
            "token_uri": "${{ secrets.TOKEN_URI }}"
          }' > credentials.json

      - name: Run App
        run: python scraper.py
