name: scraper

on:
    push:

jobs:
     Daily-Ran:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout Code
               uses: actions/checkout@v4
             - name: Run App
               run: python scraper.py